#!/usr/bin/env python3
"""make_book_tables.py — emit the extra LaTeX tables the book-length report needs,
and compute the statistical-power / deflated-Sharpe analysis of Chapter 10.

Everything here is derived from CSVs already written by the analysis scripts in
scripts/analysis/ (nothing is hand-typed). Outputs:

  report/tables/engine_latency.tex    per-stage p50/p95/p99 from results/tables/engine_latency.csv
  report/tables/nonlinear_reset.tex   RESET p-values          (nonlinear_reset.csv)
  report/tables/nonlinear_learn.tex   GBM learning curve      (nonlinear_learning.csv)
  report/tables/multtest_dm.tex       Diebold-Mariano forest  (multtest_dm.csv)
  report/tables/multtest_hac.tex      per-strategy HAC audit  (multtest_audit.csv)
  report/tables/power_dsr.tex         power / deflated Sharpe (computed here)
  results/tables/power_dsr.csv        the same numbers as CSV (machine-readable)

Power / deflated-Sharpe methodology (Chapter 10 of the report):
  * required sample size T* = (z / SR_daily)^2 days, for z = 1.645 (one-sided 5%)
    and z = Phi^{-1}(1 - alpha/M) (Bonferroni over the audited M);
  * Bailey & Lopez de Prado (2014): expected maximum Sharpe under the null,
        SR0 = sqrt(V[SR]) * ((1-g) * Phi^{-1}(1-1/N) + g * Phi^{-1}(1-1/(N e))),
    and the deflated Sharpe ratio
        DSR = Phi( (SR_hat - SR0) * sqrt(T-1)
                   / sqrt(1 - skew*SR_hat + (kurt-1)/4 * SR_hat^2) );
  * effective number of independent trials from the eigenvalue spectrum of the
    (T, M) daily-P&L correlation matrix: M_eff = (sum l)^2 / sum l^2
    (the participation ratio), plus the mean pairwise correlation;
  * stationary-bootstrap percentile CI for the best strategy's Sharpe.

Run: python3 scripts/analysis/make_book_tables.py
"""
import csv
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
RTAB = os.path.join(ROOT, "report", "tables")
sys.path.insert(0, os.path.join(ROOT, "scripts"))
sys.path.insert(0, os.path.join(ROOT, "scripts", "statkit"))
os.makedirs(RTAB, exist_ok=True)

BARS_PER_YEAR = 252.0
EULER = 0.5772156649015329


def _read(name):
    p = os.path.join(TAB, name)
    if not os.path.exists(p):
        return None
    return pd.read_csv(p)


def _esc(s):
    return (str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            .replace("#", r"\#"))


def _write_table(path, caption, label, header, rows, colfmt=None, note=None):
    ncol = len(header)
    if colfmt is None:
        colfmt = "l" + "r" * (ncol - 1)
    out = [r"% Generated by scripts/analysis/make_book_tables.py -- do not edit.",
           r"\begin{table}[H]\centering\small",
           r"\begin{threeparttable}",
           rf"\caption{{{caption}}}",
           rf"\label{{{label}}}",
           rf"\begin{{tabular}}{{{colfmt}}}",
           r"\toprule",
           " & ".join(header) + r" \\",
           r"\midrule"]
    for r in rows:
        out.append(" & ".join(str(c) for c in r) + r" \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    if note:
        out.append(r"\begin{tablenotes}\footnotesize\item " + note + r"\end{tablenotes}")
    out.append(r"\end{threeparttable}")
    out.append(r"\end{table}")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(path, ROOT)}")


# --------------------------------------------------------------------------
# 1. Engine per-stage latency
# --------------------------------------------------------------------------
def table_engine_latency():
    df = _read("engine_latency.csv")
    if df is None:
        return
    rows = []
    for _, r in df.iterrows():
        rows.append([r"\texttt{" + _esc(r["stage"]) + "}",
                     f"{r['p50_ns']:.1f}", f"{r['p95_ns']:.1f}", f"{r['p99_ns']:.1f}",
                     f"{r['mean_ns']:.1f}"])
    _write_table(
        os.path.join(RTAB, "engine_latency.tex"),
        "Per-stage latency of the C++ pipeline over 30{,}000 synthetic bars "
        "(\\code{build/statarbsim --demo}). Percentiles are lower edges of "
        "logarithmically spaced histogram buckets of width $\\times1.158$ over "
        "$[10\\,\\mathrm{ns},100\\,\\mu\\mathrm{s}]$; identical p50/p95/p99 means those "
        "quantiles share one bucket, not that the distribution is degenerate.",
        "tab:engine_latency",
        ["Stage", "p50 (ns)", "p95 (ns)", "p99 (ns)", "mean (ns)"],
        rows,
        note="Source: \\code{results/tables/engine_latency.csv}, captured by "
             "\\code{scripts/analysis/capture_engine_bench.py}.")


# --------------------------------------------------------------------------
# 2. RESET test + learning curve
# --------------------------------------------------------------------------
def table_nonlinear_reset():
    df = _read("nonlinear_reset.csv")
    if df is None:
        return
    rows = []
    for _, r in df.iterrows():
        p = float(r["reset_p"])
        pstr = "$<10^{-3}$" if p < 1e-3 else f"{p:.4f}"
        verdict = "reject" if bool(r["reject_linear_at_5pct"]) else "no reject"
        rows.append([r"\texttt{" + _esc(r["basket"]) + "}", f"{int(r['n_train'])}",
                     pstr, verdict])
    _write_table(
        os.path.join(RTAB, "nonlinear_reset.tex"),
        "Ramsey RESET $F$-test of the linear forecasting equation, fitted on the "
        "training sample only ($H_0$: no omitted nonlinearity). Linearity survives on "
        "the \\texttt{ADBE} basket used throughout Phases 4--8 and is rejected on the "
        "other three.",
        "tab:nonlinear_reset",
        ["Basket", "$n_{\\text{train}}$", "RESET $p$", "Verdict at 5\\%"],
        rows, "lrrl",
        note="Source: \\code{results/tables/nonlinear_reset.csv} via "
             "\\code{scripts/analysis/compare_nonlinear.py}.")


def table_nonlinear_learning():
    df = _read("nonlinear_learning.csv")
    if df is None:
        return
    rows = [[f"{int(r['train_bars'])}", f"{r['oos_mse']:.3e}", f"{r['oos_r2']:+.4f}"]
            for _, r in df.iterrows()]
    _write_table(
        os.path.join(RTAB, "nonlinear_learn.tex"),
        "Gradient-boosting learning curve: out-of-sample fit on a fixed 2019--2020 "
        "validation window as the causal training sample grows. The ensemble is still "
        "inside its own variance-dominated regime until roughly 2{,}400--2{,}800 "
        "training bars, which is about as much data as this universe provides.",
        "tab:nonlinear_learning",
        ["Training bars", "OOS MSE", "OOS $R^2$"],
        rows, "rrr",
        note="Source: \\code{results/tables/nonlinear_learning.csv}.")


# --------------------------------------------------------------------------
# 3. Diebold-Mariano forest + HAC audit
# --------------------------------------------------------------------------
def table_multtest_dm():
    df = _read("multtest_dm.csv")
    if df is None:
        return
    rows = []
    for _, r in df.iterrows():
        if _esc(r["other"]) == _esc(r["ref"]):
            continue
        dm = "---" if pd.isna(r["dm"]) else f"{r['dm']:+.3f}"
        p = "---" if pd.isna(r["p"]) else f"{r['p']:.4f}"
        rows.append([r"\texttt{" + _esc(r["other"]) + "}",
                     f"{r['mean_diff_daily']:+.3f}", f"{r['hac_se_daily']:.3f}",
                     dm, p,
                     "yes" if bool(r["ref_better"]) else "no"])
    _write_table(
        os.path.join(RTAB, "multtest_dm.tex"),
        "Diebold--Mariano comparison on the \\texttt{ADBE} basket: mean daily "
        "\\emph{net} P\\&L difference between the best within-basket hedge "
        "(Kalman $q=10^{-5}$) and each alternative, with Newey--West HAC standard "
        "errors. No pair is statistically distinguishable; every 95\\% interval spans "
        "zero.",
        "tab:multtest_dm",
        ["Alternative hedge", "Mean diff (bps/day)", "HAC s.e.", "DM stat", "$p$",
         "Ref.\\ better?"],
        rows, "lrrrrc",
        note="Source: \\code{results/tables/multtest_dm.csv} via "
             "\\code{scripts/analysis/compare_multtest.py}.")


def table_multtest_hac():
    df = _read("multtest_audit.csv")
    if df is None:
        return
    rows = []
    for _, r in df.iterrows():
        rows.append([r"\texttt{" + _esc(r["basket"]) + "}",
                     r"\texttt{" + _esc(r["model"]) + "}",
                     f"{r['net_sharpe_full']:+.3f}", f"{r['ann_ret_full']:+.4f}",
                     f"{r['mean_daily_bps']:+.2f}", f"{r['hac_t_full']:+.3f}",
                     f"{r['p_mean_gt0']:.4f}", f"{r['test_sharpe_net']:+.3f}"])
    _write_table(
        os.path.join(RTAB, "multtest_hac.tex"),
        "The complete audited hypothesis set: all $M=44$ (basket $\\times$ hedge) "
        "strategies actually traded across Phases 4--9, aligned on a common daily "
        "calendar and net of 10\\,bps one-way cost. HAC $t$ and one-sided $p$ test "
        "$H_0$: mean daily net P\\&L $\\le 0$. The best raw $p$ in the whole set is "
        "$0.059$; the Bonferroni bar is $0.00114$.",
        "tab:multtest_hac",
        ["Basket", "Hedge", "Net SR", "Ann.\\ net", "bps/day", "HAC $t$",
         "$p$ (1-sided)", "Net SR 2022+"],
        rows, "llrrrrrr",
        note="Source: \\code{results/tables/multtest_audit.csv}. Sorted by full-sample "
             "net Sharpe, descending.")


# --------------------------------------------------------------------------
# 4. Power analysis + deflated Sharpe ratio
# --------------------------------------------------------------------------
def _norm_ppf(q):
    from scipy.stats import norm
    return float(norm.ppf(q))


def _norm_cdf(x):
    from scipy.stats import norm
    return float(norm.cdf(x))


def power_and_dsr():
    audit = _read("multtest_audit.csv")
    corr = _read("multtest_corrections.csv")
    pnl = _read("multtest_pnl.csv")
    if audit is None or corr is None:
        print("[skip] power analysis: multtest tables not present")
        return
    d = {r["quantity"]: r["value"] for _, r in corr.iterrows()}
    M = int(d.get("n_hypotheses_M", len(audit)))
    T = int(d.get("n_days_T", 0))

    best = audit.iloc[0]
    sr_ann = float(best["net_sharpe_full"])
    sr_d = sr_ann / np.sqrt(BARS_PER_YEAR)

    rows_csv = []
    rows_tex = []

    def add(q, v, detail):
        rows_csv.append({"quantity": q, "value": v, "detail": detail})
        rows_tex.append([r"\code{" + _esc(q) + "}", _esc(v), _esc(detail)])

    add("n_trials_M", M, "audited (basket x hedge) strategies")
    add("T_common_days", T, "aligned daily observations per strategy")
    add("best_strategy", f"{best['basket']}::{best['model']}",
        "highest full-sample net Sharpe in the audited set")
    add("best_net_sharpe_ann", round(sr_ann, 3), "annualised, net of 10 bps one-way")
    add("best_daily_sharpe", round(sr_d, 5), "per-bar, the unit used in T*")

    # --- required sample size, uncorrected and Bonferroni-corrected ---
    z05 = _norm_ppf(0.95)
    zbonf = _norm_ppf(1.0 - 0.05 / M)
    t_req = (z05 / sr_d) ** 2 if sr_d > 0 else float("inf")
    t_req_b = (zbonf / sr_d) ** 2 if sr_d > 0 else float("inf")
    add("T_star_days_5pct", int(round(t_req)),
        "days needed for one-sided 5% significance, uncorrected")
    add("T_star_years_5pct", round(t_req / BARS_PER_YEAR, 1), "same, in years")
    add("z_bonferroni", round(zbonf, 3), f"critical value at alpha/M = {0.05 / M:.6f}")
    add("T_star_days_bonferroni", int(round(t_req_b)),
        "days needed after Bonferroni over M trials")
    add("T_star_years_bonferroni", round(t_req_b / BARS_PER_YEAR, 1), "same, in years")

    # --- same calculation for the best ADBE variant (the report's main basket) ---
    adbe = audit[audit["basket"] == "ADBE"]
    if len(adbe):
        b2 = adbe.iloc[0]
        sr2 = float(b2["net_sharpe_full"]) / np.sqrt(BARS_PER_YEAR)
        add("best_ADBE_strategy", f"{b2['basket']}::{b2['model']}",
            f"net Sharpe {b2['net_sharpe_full']:+.3f}")
        if sr2 > 0:
            add("T_star_years_ADBE_5pct", round((z05 / sr2) ** 2 / BARS_PER_YEAR, 0),
                "years of daily data for the best ADBE variant, uncorrected")
            add("T_star_years_ADBE_bonferroni",
                round((zbonf / sr2) ** 2 / BARS_PER_YEAR, 0),
                "years of daily data for the best ADBE variant, Bonferroni-corrected")

    # --- expected maximum of M null t-statistics ---
    add("E_max_t_null_indep", round(np.sqrt(2 * np.log(M)), 2),
        "sqrt(2 ln M): expected best t-stat if all M were independent noise")
    add("best_hac_t_observed", float(best["hac_t_full"]),
        "observed best HAC t (below the independent-noise benchmark)")

    # --- dependence structure of the audited set ---
    if pnl is not None and pnl.shape[1] > 2:
        X = pnl.select_dtypes(include=[float]).values
        X = X[~np.isnan(X).any(axis=1)]
        if X.shape[0] > 50:
            C = np.corrcoef(X, rowvar=False)
            iu = np.triu_indices_from(C, k=1)
            mean_rho = float(np.mean(C[iu]))
            w, _ = np.linalg.eigh(C)
            w = np.clip(w, 1e-12, None)
            m_eff = float((w.sum() ** 2) / (w ** 2).sum())   # participation ratio
            add("mean_pairwise_corr", round(mean_rho, 3),
                "average correlation between the daily net P&L of two audited strategies")
            add("M_effective", round(m_eff, 1),
                "participation ratio of the P&L correlation spectrum (independent trials)")
            add("E_max_t_null_Meff", round(np.sqrt(2 * np.log(max(m_eff, 1.0001))), 2),
                "expected best t-stat if the set behaved like M_eff independent nulls")

            # --- deflated Sharpe ratio (Bailey & Lopez de Prado 2014) ---
            srs = (audit["net_sharpe_full"].astype(float).values
                   / np.sqrt(BARS_PER_YEAR))
            V_sr = float(np.var(srs, ddof=1))
            N = M
            sr0 = np.sqrt(V_sr) * ((1 - EULER) * _norm_ppf(1 - 1.0 / N)
                                   + EULER * _norm_ppf(1 - 1.0 / (N * np.e)))
            add("V_sharpe_across_trials", round(V_sr, 8),
                "variance of the per-bar Sharpe across the M audited strategies")
            add("SR0_expected_max_null", round(sr0 * np.sqrt(BARS_PER_YEAR), 4),
                "expected best annualised Sharpe under the null, BLP formula")

            col = f"{best['basket']}::{best['model']}"
            skew = kurt = np.nan
            dsr = np.nan
            if col in pnl.columns:
                r = pnl[col].dropna().values
                skew = float(pd.Series(r).skew())
                kurt = float(pd.Series(r).kurtosis())      # excess kurtosis
                k = kurt + 3.0                             # BLP uses non-excess
                obs = float(r.mean() / r.std(ddof=1))
                denom = np.sqrt(max(1e-12,
                                    1 - skew * obs + ((k - 1) / 4.0) * obs ** 2))
                dsr = _norm_cdf((obs - sr0) * np.sqrt(len(r) - 1) / denom)
                add("best_skew_daily", round(skew, 3), "sample skewness of daily net P&L")
                add("best_excess_kurtosis_daily", round(kurt, 3),
                    "sample excess kurtosis of daily net P&L")
            add("deflated_sharpe_ratio",
                round(dsr, 4) if not np.isnan(dsr) else "n/a",
                "P(true SR > SR0); the conventional bar is >0.95")

            # --- stationary-bootstrap percentile CI on the best Sharpe ---
            try:
                import bootstrap as sb
                if col in pnl.columns:
                    r = pnl[col].dropna().values
                    idx = sb.stationary_bootstrap(len(r), n_boot=1200, mean_block=10,
                                                  rng=np.random.default_rng(11))

                    def _sr(v):
                        s = v.std(ddof=1)
                        return float(v.mean() / s * np.sqrt(BARS_PER_YEAR)) if s > 0 else 0.0

                    draws = np.array([_sr(r[i]) for i in idx])
                    lo, hi = np.percentile(draws, [2.5, 97.5])
                    add("boot_sharpe_ci95_lo", round(float(lo), 3),
                        "stationary-bootstrap percentile CI (mean block 10, 1200 draws)")
                    add("boot_sharpe_ci95_hi", round(float(hi), 3),
                        "upper end of the same interval")
            except Exception as exc:                              # pragma: no cover
                print(f"[warn] bootstrap CI skipped: {exc}")

    pd.DataFrame(rows_csv).to_csv(os.path.join(TAB, "power_dsr.csv"), index=False)
    print(f"wrote {os.path.relpath(os.path.join(TAB, 'power_dsr.csv'), ROOT)}")

    _write_table(
        os.path.join(RTAB, "power_dsr.tex"),
        "Statistical power and the deflated Sharpe ratio for the audited set. "
        "$T^{\\ast}$ inverts $t=\\mathrm{SR}_{\\text{daily}}\\sqrt{T}$: the number of "
        "daily observations needed for the observed Sharpe to be significant. The "
        "deflated Sharpe ratio (Bailey \\& L\\'opez de Prado) asks whether the best "
        "observed Sharpe exceeds what selecting the maximum of $M$ trials would produce "
        "from noise alone.",
        "tab:power_dsr",
        ["Quantity", "Value", "Meaning"],
        rows_tex, "p{0.30\\linewidth}rp{0.44\\linewidth}",
        note="Computed by \\code{scripts/analysis/make_book_tables.py} from "
             "\\code{results/tables/multtest_*.csv}; machine-readable copy in "
             "\\code{results/tables/power_dsr.csv}.")


def main():
    table_engine_latency()
    table_nonlinear_reset()
    table_nonlinear_learning()
    table_multtest_dm()
    table_multtest_hac()
    power_and_dsr()
    return 0


if __name__ == "__main__":
    sys.exit(main())
