#!/usr/bin/env python3
"""Render the synthetic-validation table fragment for the report appendix from
results/tables/statkit_validation.csv. Called by report/build_report.py."""
import os

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
OUT = os.path.join(ROOT, "report", "tables")

LABELS = {
    "ou_true_theta": r"OU speed $\theta$ (true)",
    "ou_est_theta": r"OU speed $\hat\theta$ (est.)",
    "ou_est_halflife": r"Estimated half-life $\ln 2/\hat\theta$",
    "ou_halflife_true_ln2/theta": r"True half-life $\ln 2/\theta$",
    "stationarity_AR1_label": r"Joint ADF/KPSS label (stationary AR(1))",
    "coint_hedge_beta_est": r"Engle--Granger hedge $\beta$ (true 2.0)",
    "coint_eg_adf_pvalue": r"EG residual ADF p-value",
    "dm_statistic": r"Diebold--Mariano statistic (model 1 better)",
    "dm_pvalue": r"DM p-value",
    "rc_pvalue_all_null": r"Reality Check p-value (all $M$ null)",
    "rc_pvalue_with_real_edge": r"Reality Check p-value (one real edge)",
}


def main():
    df = pd.read_csv(os.path.join(TAB, "statkit_validation.csv"))
    lines = []
    lines.append("% Auto-generated by scripts/plotting/render_method_validation.py")
    lines.append("")
    lines.append("\\begin{table}[H]\\centering\\small")
    lines.append("\\caption{Synthetic-data validation of the statistical toolkit "
                 "(\\texttt{scripts/statkit/}). On simulated data the routines recover "
                 "the true parameters and, crucially, the Reality Check is "
                 "\\emph{non}-significant under an all-null scan while detecting a "
                 "genuine edge.}")
    lines.append("\\label{tab:statkit_validation}")
    lines.append("\\begin{tabular}{lr}\\toprule")
    lines.append("\\textbf{Check} & \\textbf{Value}\\\\ \\midrule")
    for _, r in df.iterrows():
        label = LABELS.get(r["check"], r["check"].replace("_", " "))
        lines.append(f"{label} & {r['value']} \\\\")
    lines.append("\\bottomrule\\end{tabular}\\end{table}")
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "method_validation.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote report/tables/method_validation.tex")


if __name__ == "__main__":
    main()
