#!/usr/bin/env python3
"""Render the Part 4 single-basket backtest results: gross vs net equity curve,
cost-sensitivity of Sharpe, and a LaTeX results table for report Section 7."""
import os
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
FIG = os.path.join(ROOT, "results", "figures")
BKT = os.path.join(ROOT, "results", "backtests")
REPORT_FIG = os.path.join(ROOT, "report", "figures")
REPORT_TAB = os.path.join(ROOT, "report", "tables")


def main():
    summary = pd.read_csv(os.path.join(TAB, "backtest_summary.csv"))
    series = pd.read_csv(os.path.join(BKT, "ADBE_main.csv"))
    engine_csv = os.path.join(ROOT, "data", "processed", "engine", "ADBE.csv")
    dates = pd.read_csv(engine_csv, usecols=["date"])["date"]

    if len(dates) >= len(series):
        dates = dates.iloc[:len(series)].reset_index(drop=True)
    series = series.iloc[:len(dates)].copy()
    series["date"] = pd.to_datetime(dates)

    os.makedirs(FIG, exist_ok=True)
    os.makedirs(REPORT_FIG, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    # --- equity curve gross vs net (NAV = exp(lognav)), cost 10 bps ---
    series["nav_gross"] = np.exp(series["lognav_gross"])
    series["nav_net"] = np.exp(series["lognav_net"])
    fig, ax = plt.subplots(figsize=(10, 4.5))
    ax.plot(series["date"], series["nav_gross"], label="Gross of costs", lw=1.4, color="#4C72B0")
    ax.plot(series["date"], series["nav_net"], label="Net of costs (10 bps one-way)", lw=1.4, color="#C44E52")
    ax.set_yscale("log")
    ax.set_title("Spread stat-arb, target ADBE vs basket {CRM, ADSK, INTU} (walk-forward, no lookahead)")
    ax.set_ylabel("NAV ($1 per $1 gross, log scale)")
    ax.legend()
    ax.grid(True, which="both", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "equity_curve.png"), dpi=150)
    plt.close(fig)

    # --- cost sensitivity of net Sharpe ---
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(summary["cost_way_bps"], summary["net_sharpe"], "-o", color="#55A868")
    ax.axhline(0, color="k", lw=0.8)
    ax.axhline(summary.loc[summary["cost_way_bps"] == 0, "gross_sharpe"].iloc[0],
               ls="--", color="#4C72B0", label="Gross Sharpe")
    ax.set_xlabel("One-way cost (bps)")
    ax.set_ylabel("Net Sharpe (annualized)")
    ax.set_title("Net Sharpe vs transaction cost")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "cost_sensitivity.png"), dpi=150)
    plt.close(fig)

    for f in ("equity_curve.png", "cost_sensitivity.png"):
        shutil.copy2(os.path.join(FIG, f), os.path.join(REPORT_FIG, f))

    # --- LaTeX table fragment ---
    base = summary[summary["cost_way_bps"] == 10.0].iloc[0]
    lines = ["% Auto-generated by scripts/plotting/render_backtest.py",
             "\\begin{table}[H]\\centering\\small",
             "\\caption{Spread stat-arb backtest, target \\texttt{ADBE} vs basket "
             "\\{\\texttt{CRM}, \\texttt{ADSK}, \\texttt{INTU}\\}, 2010-01-04 .. 2026-09-01 "
             "(%d bars, window 120d, entry/exit z = 2.0/0.5). Gross and net-of-cost metrics; "
             "one-way cost 10 bps.}%%" % int(series["nav_net"].notna().sum())]
    lines.append("\\label{tab:backtest_base}")
    lines.append("\\begin{tabular}{lcc}\\toprule")
    lines.append("\\textbf{Metric} & \\textbf{Gross} & \\textbf{Net}\\\\ \\midrule")
    lines.append("Annualized log-return & %.4f & %.4f \\\\" % (base["gross_ann_ret"], base["net_ann_ret"]))
    lines.append("Sharpe (annualized) & %.3f & %.3f \\\\" % (base["gross_sharpe"], base["net_sharpe"]))
    lines.append("Max drawdown (log) & -- & %.3f \\\\" % base["maxdd"])
    lines.append("Number of round trips & \\multicolumn{2}{c}{%d}\\\\" % int(base["trades"]))
    lines.append("Avg holding (bars) & \\multicolumn{2}{c}{%.1f}\\\\" % base["avg_hold"])
    lines.append("\\bottomrule\\end{tabular}\\end{table}")
    lines.append("")
    lines.append("\\begin{table}[H]\\centering\\small")
    lines.append("\\caption{Cost sensitivity: annualized net Sharpe vs one-way cost "
                 "(bps) -- the edge is quickly eroded by realistic costs.}")
    lines.append("\\label{tab:cost_sensitivity}")
    lines.append("\\begin{tabular}{ccccc}\\toprule")
    lines.append("\\textbf{Cost (bps)} & 0 & 5 & 10 & 20 \\\\ \\midrule")
    sh = [summary[summary["cost_way_bps"] == c]["net_sharpe"].iloc[0] for c in (0, 5, 10, 20)]
    lines.append("Net Sharpe & %.2f & %.2f & %.2f & %.2f \\\\" % tuple(sh))
    lines.append("\\bottomrule\\end{tabular}\\end{table}")
    os.makedirs(REPORT_TAB, exist_ok=True)
    with open(os.path.join(REPORT_TAB, "backtest_base.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote results/figures/{equity_curve,cost_sensitivity}.png + report/tables/backtest_base.tex")


if __name__ == "__main__":
    main()
