#!/usr/bin/env python3
"""Render Part 8 Kalman figures + LaTeX table from the live run.

Reads results/tables/kalman_summary.csv and results/model/beta_kalman.csv and writes:
  results/figures/kalman_beta.png       filtered beta path vs rolling-OLS beta (CRM)
  results/figures/kalman_sharpe.png     full-sample & test net Sharpe, Kalman q-grid vs
                                        rolling OLS/Ridge
  report/tables/kalman.tex              comparison table
"""
import os
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
MODEL = os.path.join(ROOT, "results", "model")
FIG = os.path.join(ROOT, "results", "figures")
REPORT_FIG = os.path.join(ROOT, "report", "figures")
REPORT_TAB = os.path.join(ROOT, "report", "tables")


def main():
    summ = pd.read_csv(os.path.join(TAB, "kalman_summary.csv"))
    kb = pd.read_csv(os.path.join(MODEL, "beta_kalman.csv"), parse_dates=["date"])
    ob = pd.read_csv(os.path.join(MODEL, "beta_ols.csv"), parse_dates=["date"]) \
        if os.path.exists(os.path.join(MODEL, "beta_ols.csv")) else None

    os.makedirs(FIG, exist_ok=True)
    os.makedirs(REPORT_FIG, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    # ---- fig 1: filtered beta (CRM) vs rolling OLS ----
    fig, ax = plt.subplots(figsize=(10, 4))
    if ob is not None:
        ax.plot(ob["date"], ob["CRM"], label="rolling OLS w120 (CRM)",
                color="#4C72B0", lw=1.0, alpha=0.8)
    ax.plot(kb["date"], kb["CRM"], label="Kalman (CRM, q=val-selected)",
            color="#C44E52", lw=1.2)
    ax.set_title("Hedge weight on CRM over time: Kalman-filtered vs rolling-OLS window")
    ax.set_ylabel("beta (CRM)"); ax.legend(fontsize=9)
    ax.tick_params(axis="x", rotation=30)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "kalman_beta.png"), dpi=150)
    plt.close(fig)

    # ---- fig 2: net Sharpe comparison (full & test) ----
    rows = summ[summ["kind"] != "meta"].reset_index(drop=True)
    kal = rows[rows["kind"] == "kalman"]
    roll = rows[rows["kind"] == "rolling"]
    labels = list(kal["model"]) + list(roll["model"])
    full = list(kal["full_sharpe_net"]) + list(roll["full_sharpe_net"])
    test = list(kal["test_sharpe_net"]) + list(roll["test_sharpe_net"])
    x = np.arange(len(labels)); wdt = 0.4
    fig, ax = plt.subplots(figsize=(11, 4.6))
    ax.bar(x - wdt / 2, full, wdt, label="Net Sharpe, full 2010-2026", color="#4C72B0")
    ax.bar(x + wdt / 2, test, wdt, label="Net Sharpe, test 2022+", color="#C44E52")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=8)
    ax.set_ylabel("annualized net Sharpe")
    ax.set_title("Net-of-cost Sharpe: Kalman state-noise sweep vs rolling OLS/Ridge "
                 "(ADBE basket, 10 bps)")
    ax.legend(fontsize=9)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "kalman_sharpe.png"), dpi=150)
    plt.close(fig)

    for f in ("kalman_beta.png", "kalman_sharpe.png"):
        shutil.copy2(os.path.join(FIG, f), os.path.join(REPORT_FIG, f))

    # ---- LaTeX table ----
    os.makedirs(REPORT_TAB, exist_ok=True)
    L = ["% Auto-generated by scripts/plotting/render_kalman.py",
         "\\begin{table}[H]\\centering\\small",
         "\\caption{Kalman-filtered time-varying hedge vs rolling OLS/Ridge on target "
         "\\texttt{ADBE} / basket \\{\\texttt{CRM},\\texttt{ADSK},\\texttt{INTU}\\}, all "
         "no-lookahead at 10 bps one-way. Kalman's state-noise dial $q$ "
         "($Q_{ii}=q^2 R$); full = 2010-2026, test = 2022+. Lower $q$ \\emph{slows} "
         "adaptation (smoother, lower-turnover hedge); higher $q$ adapts faster and "
         "over-tracks the tradable spread.}",
         "\\label{tab:kalman_compare}",
         "\\begin{tabular}{lcccl}\\toprule",
         "\\textbf{Hedge} & \\textbf{gross} & \\textbf{net} & \\textbf{net} & "
         "\\textbf{trades} \\\\",
         " & \\textbf{(full)} & \\textbf{(full)} & \\textbf{(test)} & "
         "\\textbf{(full)} \\\\ \\midrule"]
    for _, r in rows.iterrows():
        L.append("%s & %.3f & %.3f & %.3f & %d \\\\" % (
            r["model"], r["full_sharpe_gross"], r["full_sharpe_net"],
            r["test_sharpe_net"], r["full_trades"] if pd.notna(r["full_trades"]) else 0))
    L.append("\\bottomrule\\end{tabular}\\end{table}")
    with open(os.path.join(REPORT_TAB, "kalman.tex"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote kalman figures + report/tables/kalman.tex")


if __name__ == "__main__":
    main()
