#!/usr/bin/env python3
"""Render Part 9 nonlinear-extension figures + LaTeX tables.

Reads results/tables/nonlinear_{summary,reset,trading,learning}.csv and writes:
  results/figures/nonlinear_ic.png        OOS IC by model per basket
  results/figures/nonlinear_reset.png     RESET p-values per basket (5% line)
  results/figures/nonlinear_sharpe.png    gated net-Sharpe vs baseline (full sample)
  results/figures/nonlinear_learning.png  GBM learning curve (OOS R^2 vs training bars)
  report/tables/nonlinear.tex             summary + trading tables
"""
import os
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
FIG = os.path.join(ROOT, "results", "figures")
REPORT_FIG = os.path.join(ROOT, "report", "figures")
REPORT_TAB = os.path.join(ROOT, "report", "tables")
BASKETS = ["ADBE", "AVGO", "GS", "CAT"]
MC = {"linear": "#4C72B0", "gbm": "#55A868", "mlp": "#8172B3"}


def main():
    summ = pd.read_csv(os.path.join(TAB, "nonlinear_summary.csv"))
    reset = pd.read_csv(os.path.join(TAB, "nonlinear_reset.csv"))
    trade = pd.read_csv(os.path.join(TAB, "nonlinear_trading.csv"))
    lc = pd.read_csv(os.path.join(TAB, "nonlinear_learning.csv"))

    os.makedirs(FIG, exist_ok=True)
    os.makedirs(REPORT_FIG, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    # ---- fig 1: OOS IC by model per basket ----
    fig, ax = plt.subplots(figsize=(9, 4.4))
    x = np.arange(len(BASKETS)); w = 0.26
    for i, m in enumerate(["linear", "gbm", "mlp"]):
        sub = summ[summ["model"] == m].set_index("basket").reindex(BASKETS)
        ic = sub["oos_ic"].values
        ax.bar(x + (i - 1) * w, ic, w, label=m, color=MC[m])
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(x); ax.set_xticklabels(BASKETS)
    ax.set_ylabel("OOS IC, R^{h=5}_{t} forecast (test 2022+)")
    ax.set_title("Linear beats nonlinear reversion forecast in every basket")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "nonlinear_ic.png"), dpi=150)
    plt.close(fig)

    # ---- fig 2: RESET p-values ----
    r = reset.set_index("basket").reindex(BASKETS)
    fig, ax = plt.subplots(figsize=(7, 4))
    bars = ax.bar(BASKETS, r["reset_p"], color=["#55A868" if v else "#C44E52"
                                                for v in r["reject_linear_at_5pct"]])
    ax.axhline(0.05, color="k", ls="--", lw=1.4)
    ax.text(3.4, 0.06, "5%", color="k")
    ax.set_ylabel("Ramsey RESET p-value")
    ax.set_title("RESET: does the linear forecast leave omitted nonlinearity?")
    for b, v in zip(bars, r["reset_p"]):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.01, f"{v:.3f}",
                ha="center", fontsize=9)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "nonlinear_reset.png"), dpi=150)
    plt.close(fig)

    # ---- fig 3: gated net Sharpe (full) ----
    full = trade[trade["scope"].str.contains("full")].set_index("config")
    order = ["z-threshold (Part-4 baseline)", "z + linear-gate", "z + gbm-gate",
             "z + mlp-gate"]
    sh = [full.loc[c, "net_sharpe"] for c in order if c in full.index]
    labs = [c.split(" (Part-4 baseline)")[0].replace("z + ", "") for c in order
            if c in full.index]
    labs = [c.replace("z-threshold", "baseline") for c in labs]
    fig, ax = plt.subplots(figsize=(7, 4))
    bars = ax.bar(labs, sh, color=MC.get("linear", "#4C72B0"))
    ax.axhline(0, color="k", lw=0.8)
    ax.set_ylabel("Net Sharpe (full 2010-2026, 10 bps)")
    ax.set_title("Forecaster-gating the z-threshold book does NOT add net value")
    for b, v in zip(bars, sh):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.003, f"{v:.3f}",
                ha="center", fontsize=9)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "nonlinear_sharpe.png"), dpi=150)
    plt.close(fig)

    # ---- fig 4: learning curve ----
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(lc["train_bars"], lc["oos_r2"], "-o", color="#55A868")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xlabel("GBM training bars (expanding, ending before 2019)")
    ax.set_ylabel("OOS R^2 on 2019-2020")
    ax.set_title("GBM learning curve: needs ~2.8k bars to turn positive OOS R^2")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "nonlinear_learning.png"), dpi=150)
    plt.close(fig)

    for f in ("nonlinear_ic.png", "nonlinear_reset.png", "nonlinear_sharpe.png",
              "nonlinear_learning.png"):
        shutil.copy2(os.path.join(FIG, f), os.path.join(REPORT_FIG, f))

    # ---- LaTeX tables ----
    os.makedirs(REPORT_TAB, exist_ok=True)
    L = ["% Auto-generated by scripts/plotting/render_nonlinear.py",
         "\\begin{table}[H]\\centering\\small",
         "\\caption{Out-of-sample (2022+) forecast quality, $R_t^{h=5}$ (realized "
         "5-bar short-side spread reversion return), per basket and estimator. "
         "IC = Pearson correlation; R$^2$ vs the test-period mean. The linear Ridge "
         "baseline beats both nonlinear estimators in every basket; the nonlinear "
         "models' out-of-sample R$^2$ is negative (overfit) in most baskets.}",
         "\\label{tab:nonlinear_forecast}",
         "\\begin{tabular}{lccccc}\\toprule",
         "\\textbf{Basket} & \\multicolumn{2}{c}{\\textbf{linear}} & "
         "\\multicolumn{2}{c}{\\textbf{GBM}} & \\textbf{MLP}\\\\",
         " & IC & R$^2$ & IC & R$^2$ & IC \\\\ \\midrule"]
    for b in BASKETS:
        row = summ[summ["basket"] == b].set_index("model")
        mlp = row.loc["mlp", "oos_ic"] if "mlp" in row.index else float("nan")
        mlp_s = ("%.3f" % mlp) if mlp == mlp else "---"
        line = "%s & %.3f & %.3f & %.3f & %.3f & %s \\\\" % (
            b, row.loc["linear", "oos_ic"], row.loc["linear", "oos_r2"],
            row.loc["gbm", "oos_ic"], row.loc["gbm", "oos_r2"], mlp_s)
        L.append(line)
    L.append("\\bottomrule\\end{tabular}\\end{table}")

    # trading table (full + test)
    L.append("")
    L.append("\\begin{table}[H]\\centering\\small")
    L.append("\\caption{Net-of-cost (10 bps one-way) book on the ADBE basket, full "
             "2010--2026 and out-of-sample 2022+, comparing the plain z-threshold "
             "entry (Part 4) with the same book gated so entries additionally require "
             "the forecaster to confirm reversion. Gating drops trades but does not "
             "raise net Sharpe.}")
    L.append("\\label{tab:nonlinear_trade}")
    L.append("\\begin{tabular}{lccc}\\toprule")
    L.append("\\textbf{Config} & \\textbf{Scope} & \\textbf{Net Sharpe} & "
             "\\textbf{Trades}\\\\ \\midrule")
    for _, r in trade.iterrows():
        L.append("%s & %s & %.3f & %d \\\\" % (
            r["config"].replace("_", "\\_").replace(" (Part-4 baseline)", ""),
            r["scope"].replace("_", "\\_"), r["net_sharpe"], int(r["trades"])))
    L.append("\\bottomrule\\end{tabular}\\end{table}")
    with open(os.path.join(REPORT_TAB, "nonlinear.tex"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote 4 nonlinear figures + report/tables/nonlinear.tex")


if __name__ == "__main__":
    main()
