#!/usr/bin/env python3
"""Render Part 10 multiple-testing + Diebold-Mariano figures and LaTeX tables.

Reads results/tables/multtest_{audit,corrections,dm}.csv and writes:
  results/figures/multtest_sharpe.png    top net Sharpe among the scanned strategies
  results/figures/multtest_pvalues.png   raw HAC p-values vs Bonferroni bar
  results/figures/multtest_forest.png    DM forest: ADBE best hedge vs the others
  report/tables/multtest.tex             audit + corrections LaTeX tables
"""
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
FIG = os.path.join(ROOT, "results", "figures")
REPORT_TAB = os.path.join(ROOT, "report", "tables")
BASKET_COLOR = {"ADBE": "#4C72B0", "AVGO": "#55A868", "GS": "#8172B3", "CAT": "#CC6677"}


def _q(s, default=0.0):
    s = str(s)
    return default if s in ("", "nan", "NaN") else float(s)


def main():
    audit = pd.read_csv(os.path.join(TAB, "multtest_audit.csv"))
    corr = pd.read_csv(os.path.join(TAB, "multtest_corrections.csv"))
    dm = pd.read_csv(os.path.join(TAB, "multtest_dm.csv"))
    os.makedirs(FIG, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    M = int(corr[corr["quantity"] == "n_hypotheses_M"]["value"].iloc[0])

    # ---- fig 1: top-12 net Sharpe by basket ----
    top = audit.head(12)
    fig, ax = plt.subplots(figsize=(9.5, 4.6))
    colors = [BASKET_COLOR[b] for b in top["basket"]]
    labels = [f"{b}·{m}" for b, m in zip(top["basket"], top["model"])]
    bars = ax.bar(labels, top["net_sharpe_full"], color=colors)
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=8)
    ax.set_ylabel("Full-sample net Sharpe (10 bps)")
    ax.set_title("Best of M=%d scanned strategies — none individually significant"
                 " (GS·OLS-w180 raw p=0.059)" % M)
    for b, v in zip(bars, top["net_sharpe_full"]):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.008, f"{v:.2f}",
                ha="center", fontsize=7)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "multtest_sharpe.png"), dpi=150)
    plt.close(fig)

    # ---- fig 2: raw HAC p-values vs Bonferroni bar ----
    p = audit["p_mean_gt0"].values
    fig, ax = plt.subplots(figsize=(9.5, 4.4))
    x = np.arange(len(p))
    ax.bar(x, p, color="#4C72B0", alpha=0.8)
    bonf_bar = 0.05 / M
    ax.axhline(0.05, color="#C44E52", ls="--", lw=1.5, label="p<0.05 (uncorrected)")
    ax.axhline(bonf_bar, color="k", ls=":", lw=1.5,
               label=f"Bonferroni bar 0.05/{M}={bonf_bar:.4f}")
    ax.set_yscale("log")
    ax.set_ylim(1e-4, 1.2)
    ax.set_xlabel("strategy index (sorted by net Sharpe)")
    ax.set_ylabel("one-sided HAC p (mean net P&L > 0)")
    ax.set_title("Even the best of %d scanned strategies (p=%.3f) fails the "
                 "uncorrected 5%% line" % (M, np.min(p)))
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "multtest_pvalues.png"), dpi=150)
    plt.close(fig)

    # ---- fig 3: DM forest on ADBE (reference = best within-ADBE, Kalman q1e-5) ----
    dd = dm[dm["other"] != dm["ref"]].copy()
    dd = dd.sort_values("mean_diff_daily")
    y = np.arange(len(dd))
    ci = 1.96 * dd["hac_se_daily"]
    fig, ax = plt.subplots(figsize=(9, 6))
    ax.errorbar(dd["mean_diff_daily"], y, xerr=ci, fmt="o", ms=5,
                color="#4C72B0", ecolor="#AAAAAA", capsize=3)
    ax.axvline(0, color="k", lw=0.9)
    ax.set_yticks(y)
    ax.set_yticklabels([o.replace("_", "-") for o in dd["other"]], fontsize=9)
    ax.set_xlabel("mean daily net P&L difference (bps) — Kalman q1e-5 minus other")
    ax.set_title("Diebold–Mariano forest (ADBE): no pairwise difference is "
                 "distinguishable (all 95% CIs span 0)")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "multtest_forest.png"), dpi=150)
    plt.close(fig)

    # ---- LaTeX table ----
    os.makedirs(REPORT_TAB, exist_ok=True)
    L = ["% Auto-generated by scripts/plotting/render_multtest.py",
         "\\begin{table}[H]\\centering\\small",
         "\\caption{Part 10 multiple-testing audit over M=%d scanned (basket$\\times$"
         "hedge) net-return strategies on a common calendar (Nov 2010--Sep 2026), all "
         "net of 10\\,bps. The empirical best (GS, rolling OLS w180, net Sharpe "
         "%.2f) has a raw one-sided HAC $p$ of %.3f, so it does not even reach the "
         "uncorrected 5\\%% line; after a Bonferroni correction for the scan and under "
         "the White Reality Check and Hansen SPA, no strategy survives.}" % (
             M, audit.iloc[0]["net_sharpe_full"], audit.iloc[0]["p_mean_gt0"]),
         "\\label{tab:multtest_corrections}",
         "\\begin{tabular}{lc}\\toprule \\textbf{Quantity} & \\textbf{Value}\\\\ \\midrule"]
    for _, r in corr.iterrows():
        L.append("%s & %s \\\\" % (r["quantity"], r["value"]))
    L.append("\\bottomrule\\end{tabular}\\end{table}")

    L.append("")
    L.append("\\begin{table}[H]\\centering\\small")
    L.append("\\caption{Top of the scanned-strategy audit: full-sample net Sharpe, "
             "annualised net return, one-sided HAC $t$ and $p$ for mean daily net "
             "P\\&L $>0$, and the out-of-sample (2022+) net Sharpe.}")
    L.append("\\label{tab:multtest_audit}")
    L.append("\\begin{tabular}{llccccc}\\toprule")
    L.append("\\textbf{Basket} & \\textbf{Model} & \\textbf{NetShp} & "
             "\\textbf{AnnRet} & \\textbf{HAC $t$} & \\textbf{$p$($>$0)} & "
             "\\textbf{Test NetShp}\\\\ \\midrule")
    for _, r in audit.head(10).iterrows():
        L.append("%s & %s & %.3f & %.3f & %.2f & %.3f & %.3f \\\\" % (
            r["basket"], r["model"].replace("_", "-"), r["net_sharpe_full"],
            r["ann_ret_full"], r["hac_t_full"], r["p_mean_gt0"],
            r["test_sharpe_net"]))
    L.append("\\bottomrule\\end{tabular}\\end{table}")
    with open(os.path.join(REPORT_TAB, "multtest.tex"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote 3 multtest figures + report/tables/multtest.tex")


if __name__ == "__main__":
    main()
