#!/usr/bin/env python3
"""Render the Part 5 model-comparison figures + LaTeX table from the live run.

Reads results/tables/model_compare_{summary,sweep}.csv and
results/model/beta_<method>.csv; writes:
  results/figures/model_compare_sharpe.png   gross vs net Sharpe by method (test OOS)
  results/figures/model_compare_ic.png       out-of-sample IC by method
  results/figures/model_compare_stability.png hedge-weight stability over time
  report/tables/model_compare.tex            results table for Section 5
"""
import os
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
MODEL = os.path.join(ROOT, "results", "model")
FIG = os.path.join(ROOT, "results", "figures")
REPORT_FIG = os.path.join(ROOT, "report", "figures")
REPORT_TAB = os.path.join(ROOT, "report", "tables")
BASKET = ["CRM", "ADSK", "INTU"]
ORDER = ["OLS", "Ridge", "Lasso", "ElasticNet", "PCA"]
COLOR = {"OLS": "#4C72B0", "Ridge": "#DD8452", "Lasso": "#55A868",
         "ElasticNet": "#C44E52", "PCA": "#8172B3"}


def main():
    summary = pd.read_csv(os.path.join(TAB, "model_compare_summary.csv")).set_index("method")
    os.makedirs(FIG, exist_ok=True)
    os.makedirs(REPORT_FIG, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    methods = [m for m in ORDER if m in summary.index]

    # ---- fig 1: gross vs net Sharpe (test OOS) ----
    g = [summary.loc[m, "test_sharpe_gross"] for m in methods]
    n = [summary.loc[m, "test_sharpe_net"] for m in methods]
    x = np.arange(len(methods)); w = 0.38
    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    ax.bar(x - w / 2, g, w, label="Gross of costs", color="#4C72B0")
    ax.bar(x + w / 2, n, w, label="Net of costs (10 bps)", color="#C44E52")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(x); ax.set_xticklabels(methods)
    ax.set_ylabel("Annualized Sharpe (test 2022+ , OOS)")
    ax.set_title("Hedge estimator vs net-of-cost Sharpe — target ADBE / {CRM,ADSK,INTU}")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "model_compare_sharpe.png"), dpi=150)
    plt.close(fig)

    # ---- fig 2: OOS information coefficient ----
    ics = [summary.loc[m, "test_ic_h21"] for m in methods]
    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    bars = ax.bar(methods, ics, color=[COLOR[m] for m in methods], width=0.6)
    ax.axhline(0, color="k", lw=0.8)
    ax.set_ylabel("OOS IC, 21-bar gross position return (test 2022+)")
    ax.set_title("Residual z predicts convergence direction under every hedger")
    for b, v in zip(bars, ics):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.003, f"{v:.2f}",
                ha="center", va="bottom", fontsize=9)
    ax.set_ylim(0, max(ics) * 1.25 + 0.01)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "model_compare_ic.png"), dpi=150)
    plt.close(fig)

    # ---- fig 3: hedge-weight stability over time ----
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
    axes[0].set_title("Hedge weight on CRM over time (walk-forward)")
    axes[1].set_title(r"$\|\beta_t\|_2$ hedge norm over time")
    for m in methods:
        bf = os.path.join(MODEL, f"beta_{m.lower()}.csv")
        if not os.path.exists(bf):
            continue
        b = pd.read_csv(bf, parse_dates=["date"])
        date = b["date"]
        axes[0].plot(date, b["CRM"], label=m, color=COLOR[m], lw=1.0)
        nrm = np.sqrt((b[BASKET] ** 2).sum(axis=1))
        axes[1].plot(date, nrm, label=m, color=COLOR[m], lw=1.0)
    for a in axes:
        a.legend(fontsize=8, ncol=2)
        a.tick_params(axis="x", rotation=30)
    axes[1].set_ylim(bottom=0)
    fig.suptitle("Regularization shrinks and stabilizes the basket hedge", y=1.02)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "model_compare_stability.png"), dpi=150)
    plt.close(fig)

    for f in ("model_compare_sharpe.png", "model_compare_ic.png",
              "model_compare_stability.png"):
        shutil.copy2(os.path.join(FIG, f), os.path.join(REPORT_FIG, f))

    # ---- LaTeX table fragment ----
    os.makedirs(REPORT_TAB, exist_ok=True)
    lines = ["% Auto-generated by scripts/plotting/render_model_comparison.py",
             "\\begin{table}[H]\\centering\\small",
             "\\caption{Walk-forward baseline comparison, target \\texttt{ADBE} vs "
             "basket \\{\\texttt{CRM},\\texttt{ADSK},\\texttt{INTU}\\}. Hyper-parameters "
             "selected on 2019--2021 (validation); metrics are out-of-sample on "
             "2022+. IC is the Pearson correlation of the standardized residual with "
             "the 21-bar gross position return; coef-instab is the time-mean of each "
             "hedge weight's std/|mean| over the test period.}",
             "\\label{tab:model_compare}",
             "\\begin{tabular}{lcccccc}\\toprule",
             "\\textbf{Method} & \\textbf{Penalty} & \\textbf{Gross} & \\textbf{Net} "
             "& \\textbf{IC} & \\textbf{coef-} & \\textbf{time} \\\\",
             " &  & \\textbf{Sharpe} & \\textbf{Sharpe} & \\textbf{(h=21)} & "
             "\\textbf{instab.} & (ms/fit) \\\\ \\midrule"]
    for m in methods:
        r = summary.loc[m]
        lines.append("%s & %s & %.2f & %.2f & %.3f & %.2f & %.2f \\\\" % (
            m, r["params"], r["test_sharpe_gross"], r["test_sharpe_net"],
            r["test_ic_h21"], r["coef_instab"], r["ms_per_fit"]))
    lines.append("\\bottomrule\\end{tabular}\\end{table}")
    with open(os.path.join(REPORT_TAB, "model_compare.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote 3 model-comparison figures + report/tables/model_compare.tex")


if __name__ == "__main__":
    main()
