#!/usr/bin/env python3
"""Render the report Section 3 (Data) LaTeX fragment from results.

Reads results/tables/data_summary.csv (+ sector_counts, universe_by_year) and the
figures in results/figures/, and writes report/tables/data_section.tex with a
booktabs summary table and figure includes. Called by report/build_report.py.
No hand-typed numbers: everything is read from the generated CSVs.
"""
import os

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TAB = os.path.join(ROOT, "results", "tables")
FIG = os.path.join(ROOT, "results", "figures")
OUT = os.path.join(ROOT, "report", "tables")


def value(s):
    return s["value"]


def main():
    summary = pd.read_csv(os.path.join(TAB, "data_summary.csv")).set_index("metric")["value"]
    sec = pd.read_csv(os.path.join(TAB, "sector_counts.csv"))
    by_year = pd.read_csv(os.path.join(TAB, "universe_by_year.csv"))

    get = lambda k: summary.get(k, "")
    lines = []
    lines.append("% Auto-generated by scripts/plotting/render_report_data.py — do not edit by hand.")
    lines.append("")
    lines.append("\\begin{table}[H]\\centering\\small")
    lines.append("\\caption{Dataset summary. Source: %s (retrieved via GitHub).}" % get("source"))
    lines.append("\\label{tab:data_summary}")
    lines.append("\\begin{tabular}{lr}\\toprule")
    lines.append("\\textbf{Metric} & \\textbf{Value}\\\\ \\midrule")
    rows = [
        ("Universe size (tickers)", get("n_tickers")),
        ("Number of price rows", "{:,}".format(int(float(get("rows"))))),
        ("Date range", f"{get('date_min')} -- {get('date_max')}"),
        ("Span (years)", get("span_years")),
        ("Median days per ticker", get("median_n_days_per_ticker")),
        ("Median span per ticker (yr)", get("median_n_years_per_ticker")),
        ("Tickers with $\\geq 5$ yr history (\\%)", get("pct_tickers_ge5yrs")),
        ("Cross-sectional median ann. vol. (\\%)", get("cross_sectional_median_ann_vol_pct")),
        ("Number of sectors", get("n_sectors")),
    ]
    for k, v in rows:
        lines.append(f"{k} & {v} \\\\")
    lines.append("\\bottomrule\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    lines.append("\\begin{table}[H]\\centering\\small")
    lines.append("\\caption{Sector composition of the universe.}\\label{tab:sector}")
    lines.append("\\begin{tabular}{lr}\\toprule")
    lines.append("\\textbf{Sector} & \\textbf{Tickers}\\\\ \\midrule")
    for _, r in sec.sort_values("n_tickers", ascending=False).iterrows():
        lines.append(f"{r['sector']} & {int(r['n_tickers'])} \\\\")
    lines.append("\\bottomrule\\end{tabular}\\end{table}")
    lines.append("")

    lines.append("\\begin{figure}[H]\\centering")
    lines.append("\\includegraphics[width=0.82\\linewidth]{figures/universe_by_year.png}")
    lines.append("\\caption{Number of assets with valid daily data by calendar year, from the cleaned panel.}")
    lines.append("\\label{fig:universe_year}\\end{figure}")
    lines.append("")
    lines.append("\\begin{figure}[H]\\centering")
    lines.append("\\includegraphics[width=0.85\\linewidth]{figures/sector_comp.png}")
    lines.append("\\caption{Sector composition of the universe (GICS sectors).}")
    lines.append("\\label{fig:sector}\\end{figure}")

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "data_section.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote report/tables/data_section.tex")


if __name__ == "__main__":
    main()
